#!/usr/bin/env python3
"""
Convertit des fichiers WAV en headers C pour ESP32 (PCM embarqué en flash).

Le fichier source est automatiquement converti en 16kHz mono 16-bit PCM
quel que soit le format d'origine (MP3, WAV stéréo, 44.1kHz, etc.).

Usage:
  python wav_to_header.py sounds/sneeze.wav
  python wav_to_header.py sounds/sneeze.mp3
  python wav_to_header.py sounds/                           # tous les fichiers du dossier
  python wav_to_header.py sounds/ -o src/models/gotchi/audio/sounds/

Le header généré contient:
  - Un tableau const uint8_t PROGMEM avec les données PCM brutes (16-bit LE, mono)
  - La taille en bytes
  - Le sample rate et le nombre de samples
  - Compatible avec i2s.write() directement

Dépendances:
  pip install pydub
  + ffmpeg dans le PATH (pour la conversion de formats)
"""

import argparse
import os
import sys
import struct
import wave
from pathlib import Path

def convert_to_wav_16k_mono(input_path: Path, target_sr=16000) -> bytes:
    """Convertit n'importe quel audio en PCM 16-bit mono au sample rate cible.
    Retourne les bytes PCM bruts (sans header WAV)."""

    # Utiliser pydub pour tout (gère WAV 24-bit, MP3, OGG, etc.)
    try:
        from pydub import AudioSegment
    except ImportError:
        print("Erreur: pydub requis. pip install pydub")
        sys.exit(1)

    audio = AudioSegment.from_file(str(input_path))
    audio = audio.set_frame_rate(target_sr).set_channels(1).set_sample_width(2)
    return audio.raw_data


def generate_header(name: str, pcm_data: bytes, sample_rate: int) -> str:
    """Génère le contenu du header C."""

    n_samples = len(pcm_data) // 2  # 16-bit = 2 bytes par sample
    duration_ms = (n_samples * 1000) // sample_rate

    upper = name.upper()

    lines = []
    lines.append(f'// Auto-generated by wav_to_header.py — do not edit')
    lines.append(f'// Source: {name}, {sample_rate}Hz mono 16-bit, {n_samples} samples, {duration_ms}ms')
    lines.append(f'#pragma once')
    lines.append(f'#include <cstdint>')
    lines.append(f'')
    lines.append(f'static const uint32_t {upper}_SAMPLE_RATE = {sample_rate};')
    lines.append(f'static const uint32_t {upper}_SAMPLES = {n_samples};')
    lines.append(f'static const uint32_t {upper}_DURATION_MS = {duration_ms};')
    lines.append(f'static const uint32_t {upper}_PCM_LEN = {len(pcm_data)};')
    lines.append(f'')
    lines.append(f'// PCM data: 16-bit signed LE, mono, {sample_rate}Hz')
    lines.append(f'// Pour jouer en I2S stereo, dupliquer chaque sample sur L+R')
    lines.append(f'static const uint8_t {upper}_PCM[] PROGMEM = {{')

    # Écrire les bytes, 16 par ligne
    for i in range(0, len(pcm_data), 16):
        chunk = pcm_data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'  {hex_vals},')

    lines.append(f'}};')
    lines.append(f'')

    return '\n'.join(lines)


def process_file(input_path: Path, output_dir: Path, sample_rate: int):
    """Traite un fichier audio."""

    name = input_path.stem.lower().replace('-', '_').replace(' ', '_')
    output_path = output_dir / f'sound_{name}.h'

    print(f'  {input_path.name} -> sound_{name}.h', end='')

    # Convertir en PCM
    pcm_data = convert_to_wav_16k_mono(input_path, sample_rate)

    n_samples = len(pcm_data) // 2
    duration_ms = (n_samples * 1000) // sample_rate
    size_kb = len(pcm_data) / 1024

    print(f'  ({duration_ms}ms, {n_samples} samples, {size_kb:.1f}KB)')

    # Générer le header
    header = generate_header(name, pcm_data, sample_rate)

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)

    return name, len(pcm_data), duration_ms


def main():
    parser = argparse.ArgumentParser(
        description='Convertit des fichiers audio en headers C pour ESP32')
    parser.add_argument('input', help='Fichier audio ou dossier')
    parser.add_argument('-o', '--output', default=None,
                       help='Dossier de sortie (défaut: même dossier)')
    parser.add_argument('-r', '--rate', type=int, default=16000,
                       help='Sample rate cible (défaut: 16000)')
    args = parser.parse_args()

    input_path = Path(args.input)
    audio_exts = {'.wav', '.mp3', '.ogg', '.flac', '.aac', '.m4a'}

    if input_path.is_dir():
        files = sorted([f for f in input_path.iterdir()
                       if f.suffix.lower() in audio_exts])
    elif input_path.is_file():
        files = [input_path]
    else:
        print(f'Erreur: {input_path} introuvable')
        sys.exit(1)

    if not files:
        print(f'Aucun fichier audio trouvé dans {input_path}')
        sys.exit(1)

    output_dir = Path(args.output) if args.output else input_path if input_path.is_dir() else input_path.parent

    print(f'Conversion de {len(files)} fichier(s) -> {output_dir}/')
    print(f'Format: {args.rate}Hz mono 16-bit PCM')
    print()

    total_size = 0
    results = []

    for f in files:
        name, size, dur = process_file(f, output_dir, args.rate)
        total_size += size
        results.append((name, size, dur))

    print()
    print(f'Total: {total_size/1024:.1f}KB en flash')
    print()
    print('Pour utiliser dans le code:')
    print('  #include "sounds/sound_sneeze.h"')
    print('  // Jouer: i2s.write(SNEEZE_PCM, SNEEZE_PCM_LEN)')


if __name__ == '__main__':
    main()
